nginx:
  build: ./nginx
  ports:
    - "80:80"
# expose 80 to external client client request 80 port and docker map to the server 80 port
  links:
    - "app1:app1"
    - "app2:app2"
    - "app3:app3"

app1:
  build: ./app 
# go to .app to build the image base on docker file
  ports:
    - "3000"
  links:
    - "cache:redis"

app2:
  build: ./app 
  ports:
    - "3000"
  links:
    - "cache:redis"

app3:
  build: ./app 
  ports:
    - "3000"
  links:
    - "cache:redis"

cache:
  image: redis